version: '3'
services:
  statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - "81:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: always

  myapp:
    build: .
    depends_on:
      - statsd
    environment:
      - ENV_MODE=test
      - STATSD_HOST=statsd
   
